### ISSUE TITLE
[FEATURE] View Hidden Channels

### ISSUE THREAD

**Issue by FCKJohni** [DarkGuy10/BotClient#32]
**Is your feature request related to a problem? Please describe.**
for a upcoming Roleplay Server we have very strict guidelines for User created Discords, we want to add a Bot to each of them just to make sure we can enforce those guidelines, in order to prevent the Users from just creating hidden Channels and doing forbidden stuff it would be cool to atleast see hidden Channels (reading content is not possible and we don't need that) as well as see hiden Voice Channels and their Users. (just like show hidden channels on Better Discord) Also we don't want to invite Staff to each Discord as its just toooo much work and too many Servers therefore we chose the Bot approach.

**Describe the solution you'd like**
A switch in the Console which enables the visibility of hidden channels, making them in a redish color so the BotClient User sees that this Channel is not accessible normally.

**Describe alternatives you've considered**
None, there is not really one in our case.

**Comment by SkyLayzer** [comment]
doing something like this at this stage would be a strange decision because the bot client has a bunch of errors, it can't even connect to voice channels

**Comment by FCKJohni** [comment]
Well tbh I find this much more useful than joining voice Channels, and joining Voice Channels could cause Discord to take actions against this Repo.

**Comment by DarkGuy10** [comment]
> **Is your feature request related to a problem? Please describe.** for a upcoming Roleplay Server we have very strict guidelines for User created Discords, we want to add a Bot to each of them just to make sure we can enforce those guidelines, in order to prevent the Users from just creating hidden Channels and doing forbidden stuff it would be cool to atleast see hidden Channels (reading content is not possible and we don't need that) as well as see hiden Voice Channels and their Users. (just like show hidden channels on Better Discord) Also we don't want to invite Staff to each Discord as its just toooo much work and too many Servers therefore we chose the Bot approach.
> 
> **Describe the solution you'd like** A switch in the Console which enables the visibility of hidden channels, making them in a redish color so the BotClient User sees that this Channel is not accessible normally.
> 
> **Describe alternatives you've considered** None, there is not really one in our case.

I'm pretty sure that's already a feature
Though not in "red" but channels which are private and considered normally unaccessible for the bot are shown as muted
Example:
![image](https://user-images.githubusercontent.com/62807269/158379487-0e155e46-f0aa-471c-8581-e8deaefefa85.png)

And due to missing permissions, they cannot be opened:
![image](https://user-images.githubusercontent.com/62807269/158379636-b3f34305-19a7-470e-824a-9493e8a98e47.png)

Same goes for private voice channels. They're shown with their names "muted" but you can see the participants:
![image](https://user-images.githubusercontent.com/62807269/158380228-dd736687-81a4-4e5e-aea5-634f9e335e24.png)

**Comment by DarkGuy10** [comment]
closing since the feature already exists
