### ISSUE TITLE
[FEATURE] - Allow bot to recieve and send PM

### ISSUE THREAD

**Issue by craftish37** [DarkGuy10/BotClient#36]
**Is your feature request related to a problem? Please describe.**
Bots are not able to send and recieve PM

**Describe the solution you'd like**
Well I think the name of the request is well chosen but... The bot should be able to send and recieve PM (Private Messages) (:

**Describe alternatives you've considered**
Have an interface just like the default discord :P
I can't help on the developement part, my skills in web dev are way too weak to be useful :/

**Additional context**
-

Your app is actualy damn useful, I'm already using it and is a QoL that should be in discord itself, continue like that ❤️

**Comment by craftish37** [comment]
(Well I'm damn blind, just found out how to do it, but clicks seems to be broken, can't right click on profiles :x )

**Comment by DarkGuy10** [comment]
> (Well I'm damn blind, just found out how to do it, but clicks seems to be broken, can't right click on profiles :x )

The right clicks don't work because the external lib we're using to render message is non-interactive 
Instead, we have two alternate ways of opening a DM:

### Method 1 (direct method)
Click on the [user with a +] sign on the action buttons in a message
![image](https://user-images.githubusercontent.com/62807269/160263586-7f658b20-14b8-441e-8e95-eab1686e0f5e.png)

### Method 2
Copy a user's ID from discord.com (note: you cannot right click on someone's profile in the botclient yet)
![image](https://user-images.githubusercontent.com/62807269/160263630-5828d33c-6005-4357-b6cf-f1bd51efeaa1.png)
Head to the Direct Messages section in the botclient
![image](https://user-images.githubusercontent.com/62807269/160263645-649b6f92-82bd-4c28-b356-4cae637c2ffe.png)
Paste the userID in the search box and click on the profile to open the DM
![image](https://user-images.githubusercontent.com/62807269/160263665-cf12b775-8f40-4aae-9dc8-7efd861e6b5e.png)
Profit (:
![image](https://user-images.githubusercontent.com/62807269/160263687-c31c6a6a-1f65-4599-a16d-ac4d24de2377.png)

> Your app is actualy damn useful, I'm already using it and is a QoL that should be in discord itself, continue like that :heart: 

Tysm!!
